/** Build out/dossier.json for the EntryLedger research pipeline.
 *  Receipt IDs are read from work/receipts.json (written by scripts/capture-all.ts)
 *  so no receipt identifier is ever transcribed by hand. */
import {readFile, writeFile, mkdir} from 'node:fs/promises';

const raw = JSON.parse(await readFile('work/receipts.json', 'utf8')) as Record<string, {receiptId: string; url: string}>;
const R: Record<string, string> = Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, v.receiptId]));
const T = '2026-10-08T13:45:00Z';

const ev = (
  id: string, sourceId: string, label: string,
  quote: string, locator: string,
  stance: 'supports' | 'challenges' | 'context' = 'supports',
  challengesClaimIds: string[] = [],
) => {
  const receiptId = R[label];
  if (!receiptId) throw Error(`No receipt captured for evidence label ${label}`);
  return {id, sourceId, receiptId, quote, locator, stance, challengesClaimIds, observedAt: T};
};

const dossier = {
  origin: 'research',
  subjectEntityId: 'jmccoy',
  article: {
    title: 'J. McCoy (author)',
    alternatives: ['Eligos (author)'],
    scope: 'standalone_candidate',
    scopeClaimIds: ['c_identity', 'c_pseudonym', 'c_dup', 'c_scope'],
    disambiguationClaimIds: ['c_dup', 'c_scope'],
  },
  entities: [
    {id: 'jmccoy', kind: 'person', name: 'J. McCoy', aliases: ['J McCoy']},
    {id: 'eligos', kind: 'person', name: 'Eligos', aliases: []},
    {id: 'monarch', kind: 'work', name: 'RE: Monarch', aliases: ['Monarch']},
    {id: 'dblblind', kind: 'work', name: 'Double-Blind', aliases: ['Double-Blind: A Modern LITRPG']},
    {id: 'ascension', kind: 'work', name: 'Ascension', aliases: ['Monarch IV: Ascension']},
    {id: 'aethon', kind: 'organization', name: 'Aethon Books', aliases: ['AETHON']},
    {id: 'webtoonorg', kind: 'organization', name: 'Webtoon', aliases: ['WEBTOON']},
    {id: 'moonquill', kind: 'organization', name: 'Moonquill', aliases: []},
    {id: 'daniels', kind: 'person', name: 'Luke Daniels', aliases: []},
    {id: 'summerer', kind: 'person', name: 'Eric Michael Summerer', aliases: []},
    {id: 'royalroad', kind: 'organization', name: 'Royal Road', aliases: ['RoyalRoad']},
  ],
  sources: [
    {
      id: 's_rise_author', url: 'https://www.risingshadow.net/author/13829-j-mccoy',
      title: 'J. McCoy - Author - Risingshadow',
      authors: ['Risingshadow editorial'], publisher: 'Risingshadow', kind: 'independent_secondary',
      accessed: T,
      quality: {
        assessment: 'medium',
        rationale: 'Established science-fiction and fantasy review site with named staff and its own ratings, but its coverage here is bibliographic rather than reported or analytical.',
        independenceRationale: 'Editorially separate from the author and from Aethon Books, though the author biography it reproduces is supplied promotional copy.',
        editorialOversight: true, coverage: 'passing',
        limitations: ['Author biography is publisher-supplied marketing text, not independent reporting.'],
      },
    },
    {
      id: 's_aethon_b1', url: 'https://aethonbooks.com/book/a-prince-out-of-time/',
      title: 'A Prince Out of Time | Aethon Books',
      authors: ['Aethon Books'], publisher: 'Aethon Books', kind: 'affiliated_secondary',
      published: {precision: 'day', value: '2022-04-19'},
      accessed: T,
      quality: {
        assessment: 'high',
        rationale: 'The publishing house that issued the book; its catalogue record is authoritative for bibliographic metadata.',
        independenceRationale: 'Commercially affiliated with the subject: Aethon Books publishes the series.',
        editorialOversight: true, coverage: 'substantial',
        limitations: ['Publisher marketing copy; the "beloved web serial" characterisation is promotional.'],
      },
    },
    {
      id: 's_aethon_b4', url: 'https://aethonbooks.com/book/ascension-4/',
      title: 'Ascension | Aethon Books',
      authors: ['Aethon Books'], publisher: 'Aethon Books', kind: 'affiliated_secondary',
      published: {precision: 'day', value: '2026-10-07'},
      accessed: T,
      quality: {
        assessment: 'high',
        rationale: 'Publisher catalogue record for the fourth volume; authoritative for byline and publication metadata.',
        independenceRationale: 'Commercially affiliated with the subject: Aethon Books publishes the series.',
        editorialOversight: true, coverage: 'substantial',
        limitations: ['Publisher marketing copy; narrator attribution is a catalogue claim.'],
      },
    },
    {
      id: 's_gr_eligos', url: 'https://www.goodreads.com/author/list/21514986.Eligos',
      title: 'Books by Eligos (Author of A Prince Out of Time)',
      authors: ['Goodreads users'], publisher: 'Goodreads LLC', kind: 'independent_secondary',
      accessed: T,
      quality: {
        assessment: 'medium',
        rationale: 'User-generated catalogue with very large rating volumes, but no editorial vetting of either metadata or ratings.',
        independenceRationale: 'User platform independent of the author and the publisher, though its records are built from publisher-supplied metadata.',
        editorialOversight: false, coverage: 'substantial',
        limitations: [
          'Ratings are self-selected and unaudited.',
          'Its author records duplicate the same titles under a second name.',
        ],
      },
    },
    {
      id: 's_gr_jmccoy', url: 'https://www.goodreads.com/author/list/17072655.J_McCoy',
      title: 'Books by J. McCoy (Author of A Prince Out of Time)',
      authors: ['Goodreads users'], publisher: 'Goodreads LLC', kind: 'independent_secondary',
      accessed: T,
      quality: {
        assessment: 'medium',
        rationale: 'Second parallel author record on the same platform, holding the same RE: Monarch titles and a larger cumulative rating count.',
        independenceRationale: 'User platform independent of the author and the publisher.',
        editorialOversight: false, coverage: 'substantial',
        limitations: [
          'Ratings are self-selected and unaudited.',
          'Existence of this record is itself evidence of catalogue duplication, so it is not neutral metadata.',
        ],
      },
    },
    {
      id: 's_animx', url: 'https://www.animationxpress.com/comics/webtoon-and-aethon-books-collaborate-to-adapt-14-web-novels-into-webcomics/',
      title: 'Webtoon and Aethon Books collaborate to adapt 14 web novels into webcomics',
      authors: ['AnimationXpress Team'], publisher: 'Animation Xpress India Pvt Ltd',
      kind: 'independent_secondary', published: {precision: 'day', value: '2024-01-19'},
      accessed: T,
      quality: {
        assessment: 'high',
        rationale: 'Established comics and animation trade news outlet with named editorial staff; reports the deal and quotes the Aethon CEO directly.',
        independenceRationale: 'Trade press covering an industry deal; no relationship to the author or to the retail platforms.',
        editorialOversight: true, coverage: 'substantial',
        limitations: ['Covers the adaptation industry event, not the author as a person.'],
      },
    },
    {
      id: 's_webtoon', url: 'https://www.webtoons.com/en/fantasy/re-monarch/list?title_no=6280',
      title: 'RE: Monarch | WEBTOON',
      authors: ['WEBTOON'], publisher: 'NAVER WEBTOON Ltd', kind: 'independent_secondary',
      accessed: T,
      quality: {
        assessment: 'medium',
        rationale: 'The distribution platform\'s own title page: authoritative for credits and episode dates, self-reported for audience metrics.',
        independenceRationale: 'Distributor of the adaptation and a contracting party to the deal, but not the author or the rights holder.',
        editorialOversight: false, coverage: 'passing',
        limitations: [
          'View and subscriber counts are platform self-reported and unaudited.',
          'No publication date is exposed in the extracted page text.',
        ],
      },
    },
    {
      id: 's_novellume', url: 'https://novellume.com/novel/re-monarch',
      title: 'RE: Monarch | Read Novel All Time',
      authors: ['Novellume'], publisher: 'Novellume', kind: 'tertiary',
      accessed: T,
      quality: {
        assessment: 'low',
        rationale: 'Unattributed aggregator that republishes Royal Road metadata; figures on the page are internally inconsistent.',
        independenceRationale: 'No editorial relationship to the subject, but no evident editorial standards either.',
        editorialOversight: false, coverage: 'reference',
        limitations: [
          'Reports two different rating counts for the same title on one page.',
          'Cannot be used to verify any Royal Road statistic directly.',
        ],
      },
    },
  ],
  evidence: [
    ev('ev_bio', 's_rise_author', 'E_bio_mccoy_eligos',
      'J. McCoy, who also writes under the name Eligos, crafts stories where logic, emotion, and consequence intertwine.',
      'bio'),
    ev('ev_genre_bio', 's_rise_author', 'E_bio_genre',
      'McCoy’s fiction lives at the intersection of speculative fantasy and LitRPG, creating worlds that feel alive because their rules matter and every decision changes the outcome.',
      'bio'),
    ev('ev_rr_history', 's_rise_author', 'E_bio_rr_history',
      'Long before publishing A Prince Out of Time , the first book in the RE: Monarch series, McCoy built imaginary worlds inside online games and text-based adventures, experimenting with how structure shapes storytelling.',
      'bio 2'),
    ev('ev_rise_b4', 's_rise_author', 'E_rise_b4_date',
      'Monarch IV (RE: Monarch # 4 ) 2026 | fantasy, epic fantasy, high fantasy | Release date October 7, 2026',
      'biblio'),
    ev('ev_b1_byline', 's_aethon_b1', 'E_aethon_b1_byline',
      'A Prince Out of Time RE: Monarch Book 1 By Eligos and J. McCoy', 'byline'),
    ev('ev_b1_rr', 's_aethon_b1', 'E_aethon_b1_rr',
      'After cementing itself as one of the most beloved progression fantasy web serials on Royal Road, the RE: Monarch Series now comes to Kindle, Kindle Unlimited, and Audible (narrated by Luke Daniels).',
      'blurb'),
    ev('ev_b1_meta', 's_aethon_b1', 'E_aethon_b1_meta',
      'Book Details Series RE: Monarch Author Eligos , J. McCoy Audiobook Narrator Luke Daniels Publisher Aethon Books Page Count 714',
      'details'),
    ev('ev_b1_date', 's_aethon_b1', 'E_aethon_b1_date',
      'Isbn13 9798801975511 ASIN B09PQGG7VV Publication Date April 19, 2022', 'details'),
    ev('ev_b4_byline', 's_aethon_b4', 'E_aethon_b4_byline',
      'Ascension RE: Monarch Book 4 By J. McCoy', 'byline'),
    ev('ev_b4_meta', 's_aethon_b4', 'E_aethon_b4_meta',
      'Book Details Series RE: Monarch Author J. McCoy Audiobook Narrator Eric Michael Summerer',
      'details'),
    ev('ev_b4_date', 's_aethon_b4', 'E_aethon_b4_date',
      'Isbn13 9798177705538 ASIN B0HD99YKVG Publication Date October 7, 2026', 'details'),
    ev('ev_gr_eligos_b1', 's_gr_eligos', 'E_gr_eligos_b1',
      'A Prince Out of Time (RE: Monarch #1) by J. McCoy , Eligos', 'entry 1'),
    ev('ev_gr_eligos_b4', 's_gr_eligos', 'E_gr_eligos_b4',
      'Monarch IV: Ascension: RE: Monarch, Book 4 by J. McCoy , Eric Michael Summerer (Narrator) , Eligos', 'entry 5'),
    ev('ev_gr_jmccoy_b1', 's_gr_jmccoy', 'E_gr_jmccoy_b1',
      'A Prince Out of Time (RE: Monarch #1) by J. McCoy , Eligos', 'entry 1'),
    ev('ev_gr_jmccoy_b4', 's_gr_jmccoy', 'E_gr_jmccoy_b4',
      'Monarch IV: Ascension: A Progression Fantasy Epic (RE: Monarch Book 4) by J. McCoy', 'entry 6'),
    ev('ev_animx_slate', 's_animx', 'E_animx_slate',
      'Los Angeles based digital comics platform Webtoon announced it will expand its partnership with Aethon Books, adapting a slate of 14 popular web novels as webcomics, created and produced alongside studios such as Laurel Pursuit, Moonquill, Kisai Entertainment, Cocoon Productions and more.',
      'body'),
    ev('ev_animx_mc', 's_animx', 'E_animx_mc',
      'RE: Monarch by J. McCoy – A progression fantasy epic set in a time-loop where planning and cleverness are as vital as swordplay, about a spoiled prince who discovers what it means to rule.”',
      'slate'),
    ev('ev_webtoon_credits', 's_webtoon', 'E_webtoon_credits',
      'Fantasy RE: Monarch AETHON , Moonquill , J. McCoy', 'credits'),
    ev('ev_webtoon_finale', 's_webtoon', 'E_webtoon_finale',
      'Episode 60 (Season Finale) Jul 25, 2025', 'ep list'),
    ev('ev_webtoon_synopsis', 's_webtoon', 'E_webtoon_synopsis',
      'A progression fantasy epic set in a time-loop where planning and cleverness are as vital as swordplay, about a spoiled prince who discovers what it means to rule.', 'synopsis'),
    ev('ev_webtoon_origin', 's_webtoon', 'E_webtoon_origin',
      'Created by Moonquill', 'creator'),
    ev('ev_nov_year', 's_novellume', 'E_nov_year',
      'Year of publishing: 2020', 'metadata'),
  ],
  claims: [
    {
      id: 'c_identity', category: 'identity', subjectEntityId: 'jmccoy',
      predicate: 'publishes_under', editorialRisk: 'critical',
      proposition: 'J. McCoy is the author name under which Aethon Books publishes the RE: Monarch series.',
      qualifiers: [], status: 'verified', evidenceIds: ['ev_b4_byline'], verification: 'direct',
    },
    {
      id: 'c_pseudonym', category: 'identity', subjectEntityId: 'jmccoy',
      predicate: 'also_writes_as', editorialRisk: 'high',
      proposition: 'Author biography copy states that J. McCoy also writes under the name Eligos.',
      qualifiers: ['Publisher-supplied copy, not independent reporting.'],
      status: 'verified', evidenceIds: ['ev_bio'], verification: 'direct',
    },
    {
      id: 'c_dup', category: 'disambiguation', subjectEntityId: 'jmccoy',
      predicate: 'catalogued_twice', editorialRisk: 'critical',
      proposition: 'Goodreads runs two author list pages, one for J. McCoy and one for Eligos, each carrying the same title under a joint "by J. McCoy, Eligos" byline; the names are not two authors.',
      qualifiers: ['The records also reported different rating totals, which are live counters and are therefore not quoted.'],
      status: 'verified', evidenceIds: ['ev_gr_jmccoy_b1', 'ev_gr_eligos_b1'],
      verification: 'corroborated',
    },
    {
      id: 'c_scope', category: 'scope', subjectEntityId: 'jmccoy',
      predicate: 'in_scope', editorialRisk: 'normal',
      proposition: 'One author under two names; the paired catalogue records are one metadata artefact.',
      qualifiers: [],
      status: 'verified', evidenceIds: ['ev_gr_jmccoy_b1'], verification: 'direct',
    },
    {
      id: 'c_def', category: 'definition', subjectEntityId: 'jmccoy',
      predicate: 'is_a', editorialRisk: 'high',
      proposition: 'A web-fiction author in progression fantasy and LitRPG whose RE: Monarch series ran as a Royal Road serial before commercial release.',
      qualifiers: ['Publisher claim; Royal Road unverifiable.'],
      status: 'verified', evidenceIds: ['ev_genre_bio', 'ev_b1_rr'], verification: 'corroborated',
    },
    {
      id: 'c_chrono_rr', category: 'chronology', subjectEntityId: 'monarch',
      predicate: 'serial_start', editorialRisk: 'normal',
      proposition: 'RE: Monarch began as a web serial in 2020, about two years before commercial release.',
      eventDate: {precision: 'year', value: '2020'},
      qualifiers: ['From an aggregator, not Royal Road.'],
      status: 'verified', evidenceIds: ['ev_nov_year'], verification: 'direct',
    },
    {
      id: 'c_chrono_b1', category: 'chronology', subjectEntityId: 'monarch',
      predicate: 'first_book_published', editorialRisk: 'normal',
      proposition: 'A Prince Out of Time, the first RE: Monarch book, was published on April 19, 2022.',
      eventDate: {precision: 'day', value: '2022-04-19'},
      qualifiers: [], status: 'verified', evidenceIds: ['ev_b1_date'], verification: 'direct',
    },
    {
      id: 'c_chrono_b4', category: 'chronology', subjectEntityId: 'ascension',
      predicate: 'fourth_book_published', editorialRisk: 'normal',
      proposition: 'Ascension (book 4) published October 7, 2026; audiobook October 13.',
      eventDate: {precision: 'day', value: '2026-10-07'},
      qualifiers: [], status: 'verified', evidenceIds: ['ev_b4_date', 'ev_rise_b4'], verification: 'corroborated',
    },
    {
      id: 'c_chrono_anim', category: 'chronology', subjectEntityId: 'monarch',
      predicate: 'adaptation_announced', editorialRisk: 'normal',
      proposition: 'The Webtoon adaptation was announced January 19, 2024 within a 14-title Aethon slate.',
      eventDate: {precision: 'day', value: '2024-01-19'},
      qualifiers: [], status: 'verified', evidenceIds: ['ev_animx_slate'], verification: 'direct',
    },
    {
      id: 'c_chrono_webtoon', category: 'chronology', subjectEntityId: 'monarch',
      predicate: 'season_one_finished', editorialRisk: 'normal',
      proposition: 'The adaptation reached a 60-episode first-season finale on July 25, 2025.',
      eventDate: {precision: 'day', value: '2025-07-25'},
      qualifiers: [],
      status: 'verified', evidenceIds: ['ev_webtoon_finale'], verification: 'direct',
    },
    {
      id: 'c_orgs', category: 'people_organizations', subjectEntityId: 'monarch',
      predicate: 'produced_by', editorialRisk: 'normal',
      proposition: 'Aethon Books publishes the books; the adaptation is credited to Aethon, Moonquill and J. McCoy.',
      qualifiers: [], status: 'verified', evidenceIds: ['ev_b1_meta', 'ev_webtoon_credits', 'ev_webtoon_origin'],
      verification: 'corroborated',
    },
    {
      id: 'c_narrators', category: 'people_organizations', subjectEntityId: 'monarch',
      predicate: 'narrated_by', editorialRisk: 'normal',
      proposition: 'Luke Daniels narrates the early RE: Monarch audiobooks; Eric Michael Summerer narrates Ascension.',
      qualifiers: [], status: 'verified', evidenceIds: ['ev_b1_meta', 'ev_b4_meta'], verification: 'corroborated',
    },
    {
      id: 'c_credits', category: 'relationships', subjectEntityId: 'monarch',
      predicate: 'byline_credited', editorialRisk: 'high',
      proposition: 'Publisher credits books 1-3 to "Eligos and J. McCoy" jointly, book 4 to J. McCoy alone.',
      qualifiers: ['Retail also differs on book four.'],
      status: 'verified', evidenceIds: ['ev_b1_byline', 'ev_b4_byline'], verification: 'direct',
    },
    {
      id: 'c_genre', category: 'characteristics', subjectEntityId: 'monarch',
      predicate: 'is_characterised_by', editorialRisk: 'normal',
      proposition: 'A progression-fantasy time-loop where planning, not combat, drives the plot.',
      qualifiers: ['Promotional or trade copy.'],
      status: 'verified', evidenceIds: ['ev_animx_mc', 'ev_genre_bio'], verification: 'corroborated',
    },
    {
      id: 'c_style', category: 'characteristics', subjectEntityId: 'jmccoy',
      predicate: 'draws_on', editorialRisk: 'normal',
      proposition: 'The biography credits the author\'s interest in player-driven worlds to games and text adventures predating publication.',
      qualifiers: ['Promotional copy; characterisation, not documented personal history.'],
      status: 'attributed', evidenceIds: ['ev_rr_history'], attributedTo: {type: 'source', sourceId: 's_rise_author'},
    },
    {
      id: 'c_scale', category: 'significance', subjectEntityId: 'monarch',
      predicate: 'adapted_audience', editorialRisk: 'normal',
      proposition: 'The Webtoon adaptation carries the novels\' progression-fantasy time-loop synopsis.',
      qualifiers: ['Observed 2026-10-08: 3.1M views, 106,214 subscribers. Live counters, not quoted.'],
      status: 'verified', evidenceIds: ['ev_webtoon_credits', 'ev_webtoon_synopsis'], verification: 'direct',
    },
    {
      id: 'c_trade', category: 'significance', subjectEntityId: 'monarch',
      predicate: 'trade_covered', editorialRisk: 'normal',
      proposition: 'Trade press covered the adaptation slate, naming RE: Monarch by J. McCoy.',
      qualifiers: ['Deal coverage, not author coverage.'],
      status: 'verified', evidenceIds: ['ev_animx_slate', 'ev_animx_mc'], verification: 'direct',
    },
    {
      id: 'c_reception', category: 'reception', subjectEntityId: 'monarch',
      predicate: 'reader_rated', editorialRisk: 'normal',
      proposition: 'Goodreads lists A Prince Out of Time first, under the joint J. McCoy/Eligos byline.',
      qualifiers: ['2026-10-08: 4.28 from 1,660 ratings. Live counter, not quoted.'],
      status: 'verified', evidenceIds: ['ev_gr_jmccoy_b1'], verification: 'direct',
    },
    {
      id: 'c_ascension_rating', category: 'reception', subjectEntityId: 'ascension',
      predicate: 'reader_rated', editorialRisk: 'high',
      proposition: 'Ascension had one Goodreads rating when observed on 2026-10-08, so no reception signal.',
      qualifiers: ['Count has since risen; live counter, not quoted.'],
      status: 'verified', evidenceIds: ['ev_gr_jmccoy_b4', 'ev_gr_eligos_b4'], verification: 'direct',
    },
    {
      id: 'c_controversy', category: 'controversies', subjectEntityId: 'jmccoy',
      predicate: 'independently_confirmed', editorialRisk: 'high',
      proposition: 'Whether J. McCoy and Eligos are one individual is unconfirmed by any non-promotional source.',
      question: 'Does any non-promotional source say J. McCoy and Eligos are one individual?',
      attemptIds: ['a_identity_search'],
      uncertainty: 'None. The best corroboration found, a copyright line reading "J McCoy (AKA Eligos)", is on a page the fetcher could not load.',
      qualifiers: [], status: 'unknown',
    },
    {
      id: 'c_serial_venue', category: 'limitations', subjectEntityId: 'monarch',
      predicate: 'serial_venue', editorialRisk: 'normal',
      proposition: 'The publisher names Royal Road as the series\' original serial venue.',
      qualifiers: ['Pages unreachable; no first-hand Royal Road figure.'],
      status: 'verified', evidenceIds: ['ev_b1_rr'], verification: 'direct',
    },
    {
      id: 'c_personal', category: 'limitations', subjectEntityId: 'jmccoy',
      predicate: 'has_no_sourced_biography', editorialRisk: 'critical',
      proposition: 'No personal biographical detail about the author is available from any examined source.',
      question: 'What is the author\'s legal name, nationality, age or place of residence?',
      attemptIds: ['a_bio_search'],
      uncertainty: 'No source states any personal detail; all biographical copy located is publisher-supplied.',
      qualifiers: [], status: 'unknown',
    },
  ],
  researchActions: [
    {
      id: 'a_rr_access', question: 'Can the Royal Road serial pages be verified directly as primary evidence?',
      method: 'search', performedAt: T, resolved: false, sourceIds: ['s_novellume'],
      outcome: 'royalroad.com returned HTTP 503 and then HTTP 403 to the evidence fetcher across repeated attempts. Every Royal Road figure in this dossier is therefore second-hand.',
    },
    {
      id: 'a_identity_search',
      question: 'Find a source independent of publisher-supplied copy stating J. McCoy and Eligos are one individual.',
      method: 'search', performedAt: T, resolved: false, sourceIds: ['s_rise_author'],
      outcome: 'Scribd, which carries the copyright line "J McCoy (AKA Eligos)", and Reddit both returned HTTP 403. No independent statement was retrievable; the only located statement is promotional biography text.',
    },
    {
      id: 'a_bio_search', question: 'Locate any personal biographical detail: legal name, nationality, age, residence.',
      method: 'search', performedAt: T, resolved: false, sourceIds: [],
      outcome: 'No examined source publishes personal details. Retail, review and platform pages carry only publisher-supplied promotional biography.',
    },
  ],
  coverage: [
    {category: 'identity', state: 'covered', reason: 'Publisher bylines and supplied biography establish the publication name and the Eligos relationship.', attemptIds: [], blocking: false},
    {category: 'disambiguation', state: 'covered', reason: 'Two parallel catalogue author records document the split directly.', attemptIds: [], blocking: false},
    {category: 'scope', state: 'covered', reason: 'Scope decision is grounded in the disambiguation finding.', attemptIds: [], blocking: false},
    {category: 'definition', state: 'covered', reason: 'Genre and format claims carry two supporting sources.', attemptIds: [], blocking: false},
    {category: 'chronology', state: 'covered', reason: 'Five dated events from serial start to the 2026 fourth volume.', attemptIds: ['a_rr_access'], blocking: false},
    {category: 'people_organizations', state: 'covered', reason: 'Publisher, platform, studio and narrators are each sourced.', attemptIds: [], blocking: false},
    {category: 'relationships', state: 'covered', reason: 'Byline credit differences between volumes are documented.', attemptIds: [], blocking: false},
    {category: 'characteristics', state: 'covered', reason: 'Genre characterisation is corroborated; stylistic claims are attributed to their source.', attemptIds: [], blocking: false},
    {category: 'significance', state: 'covered', reason: 'Adaptation scale and trade coverage are separately sourced.', attemptIds: [], blocking: false},
    {category: 'reception', state: 'covered', reason: 'Retail ratings sourced, with the fourth volume\'s single-rating figure flagged.', attemptIds: [], blocking: false},
    {category: 'controversies', state: 'covered', reason: 'The unresolved identity-corroboration gap is recorded as an open question with a documented search attempt.', attemptIds: ['a_identity_search'], blocking: false},
    {category: 'limitations', state: 'covered', reason: 'Serial-source access failure and the total absence of biographical detail are both recorded.', attemptIds: ['a_rr_access', 'a_bio_search'], blocking: false},
    {category: 'editorial_cautions', state: 'covered', reason: 'Six rules cover the biographical gap, the name split, reception figures and platform metrics.', attemptIds: [], blocking: false},
  ],
  editorialRules: [
    {
      id: 'r_identity', severity: 'critical', directive: 'avoid',
      text: 'Do not state personal details: no source gives a legal name, nationality, age or residence.',
      groundedClaimIds: ['c_personal'],
    },
    {
      id: 'r_no_split', severity: 'critical', directive: 'require',
      text: 'Do not split J. McCoy and Eligos into two entries; catalogues already duplicate these titles.',
      groundedClaimIds: ['c_dup', 'c_scope'],
    },
    {
      id: 'r_ascension', severity: 'high', directive: 'qualify',
      text: 'Do not report Ascension\'s 5.00 average as reception; it rests on one rating.',
      groundedClaimIds: ['c_ascension_rating'],
    },
    {
      id: 'r_bio_source', severity: 'high', directive: 'qualify',
      text: 'Attribute the J. McCoy/Eligos equivalence to the biography asserting it.',
      groundedClaimIds: ['c_pseudonym', 'c_controversy'],
    },
    {
      id: 'r_royalroad', severity: 'normal', directive: 'context',
      text: 'Attribute Royal Road figures to secondary catalogues; aggregator rating counts are unreliable.',
      groundedClaimIds: ['c_serial_venue'],
    },
  ],
  notability: {
    assessment: 'uncertain',
    rationale: 'RE: Monarch has real reach: 4.28 across 1,660 Goodreads ratings, a four-book trade series and a Webtoon adaptation in comics trade press. But every source equating J. McCoy with Eligos is publisher-supplied copy, no independent biography was found, and the Royal Road serials were unverifiable. Reach is documented; independent notability is not.',
    independentSourceIds: ['s_animx', 's_rise_author', 's_gr_jmccoy'],
    researchActionIds: ['a_rr_access', 'a_identity_search', 'a_bio_search'],
  },
  presentation: {
    requiredClaimIds: ['c_identity', 'c_dup', 'c_personal'],
    requiredRuleIds: ['r_identity', 'r_no_split'],
    weights: [
      {claimId: 'c_def', utility: 97},
      {claimId: 'c_pseudonym', utility: 95},
      {claimId: 'c_credits', utility: 93},
      {claimId: 'c_reception', utility: 88},
      {claimId: 'c_ascension_rating', utility: 90},
      {claimId: 'c_controversy', utility: 84},
      {claimId: 'c_scale', utility: 88},
      {claimId: 'c_trade', utility: 78},
      {claimId: 'c_chrono_rr', utility: 76},
      {claimId: 'c_genre', utility: 68},
      {claimId: 'c_serial_venue', utility: 66},
      {claimId: 'c_chrono_b4', utility: 62},
      {claimId: 'c_chrono_b1', utility: 58},
      {claimId: 'c_chrono_anim', utility: 56},
      {claimId: 'c_chrono_webtoon', utility: 54},
      {claimId: 'c_narrators', utility: 40},
      {claimId: 'c_style', utility: 18},
    ],
  },
};

await mkdir('out', {recursive: true});
await writeFile('out/dossier.json', JSON.stringify(dossier, null, 2) + '\n');
console.log('out/dossier.json written');
